# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-10 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad\u56fe'),
        ),
    ]
