# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-17 22:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170710_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b[\u8f6e\u64ad]',
                'proxy': True,
                'verbose_name_plural': '\u8bfe\u7a0b[\u8f6e\u64ad]',
            },
            bases=('courses.course',),
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u7a0b[\u4e0d\u8f6e\u64ad]', 'verbose_name_plural': '\u8bfe\u7a0b[\u4e0d\u8f6e\u64ad]'},
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
