# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-10 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170710_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/userinfo/default.png', null=True, upload_to='image/userinfo/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
